-- Supabase Migration Schema
-- Run this in the Supabase Dashboard SQL Editor

-- 1. Departments Table
CREATE TABLE IF NOT EXISTS public.departments (
  id VARCHAR(50) PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  code VARCHAR(50) NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Employees Table
CREATE TABLE IF NOT EXISTS public.employees (
  id VARCHAR(50) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role VARCHAR(50) NOT NULL,
  department VARCHAR(100) NOT NULL,
  avatar TEXT,
  profile_image TEXT,
  face_data TEXT,
  status VARCHAR(50) DEFAULT 'Offline',
  latitude DOUBLE PRECISION DEFAULT 0.0,
  longitude DOUBLE PRECISION DEFAULT 0.0,
  last_latitude DOUBLE PRECISION DEFAULT 0.0,
  last_longitude DOUBLE PRECISION DEFAULT 0.0,
  last_location_time TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Attendance Table
CREATE TABLE IF NOT EXISTS public.attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id VARCHAR(50) NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
  date VARCHAR(20) NOT NULL,
  check_in VARCHAR(20),
  check_out VARCHAR(20),
  working_hours DOUBLE PRECISION DEFAULT 0,
  break_duration DOUBLE PRECISION DEFAULT 0,
  overtime DOUBLE PRECISION DEFAULT 0,
  status VARCHAR(50),
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  confidence_score DOUBLE PRECISION,
  captured_image TEXT,
  device_id VARCHAR(100),
  UNIQUE(employee_id, date)
);

-- 4. Attendance Corrections Table
CREATE TABLE IF NOT EXISTS public.attendance_corrections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attendance_id INT NOT NULL,
  employee_id VARCHAR(50) NOT NULL,
  corrected_by VARCHAR(50) NOT NULL,
  reason TEXT NOT NULL,
  old_values JSONB,
  new_values JSONB,
  corrected_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Face Descriptors Table
CREATE TABLE IF NOT EXISTS public.face_descriptors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id VARCHAR(50) UNIQUE NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
  descriptor_json TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Devices Table
CREATE TABLE IF NOT EXISTS public.devices (
  id VARCHAR(100) PRIMARY KEY,
  device_name VARCHAR(100) NOT NULL,
  device_ip VARCHAR(50),
  mac_address VARCHAR(50),
  status VARCHAR(50) DEFAULT 'Active',
  last_seen TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Audit Logs Table
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id VARCHAR(50),
  event_type VARCHAR(100) NOT NULL,
  details TEXT,
  ip_address VARCHAR(50),
  timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Logs Table
CREATE TABLE IF NOT EXISTS public.logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id VARCHAR(50) REFERENCES public.employees(id) ON DELETE SET NULL,
  event_type VARCHAR(100) NOT NULL,
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  location VARCHAR(255),
  details TEXT
);

-- 9. Locations Table
CREATE TABLE IF NOT EXISTS public.locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  latitude DOUBLE PRECISION NOT NULL,
  longitude DOUBLE PRECISION NOT NULL,
  radius_meters INT DEFAULT 100,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. Settings Table
CREATE TABLE IF NOT EXISTS public.settings (
  key VARCHAR(100) PRIMARY KEY,
  value TEXT NOT NULL
);

-- 11. Office Geofence Table
CREATE TABLE IF NOT EXISTS public.office_geofence (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  office_name VARCHAR(100) NOT NULL,
  polygon_coordinates JSONB NOT NULL,
  created_by VARCHAR(50),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Default Geo-Settings Seed
INSERT INTO public.settings (key, value) VALUES 
('geofence_lat', '28.6139'),
('geofence_lng', '77.2090'),
('geofence_radius', '100')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;

-- Realtime Configuration
-- By default, Realtime is disabled on tables for security.
-- We must enable it for the tables we want to stream to the dashboard.
alter publication supabase_realtime add table public.logs;
alter publication supabase_realtime add table public.attendance;
alter publication supabase_realtime add table public.employees;

-- Row Level Security (RLS)
-- We enable RLS on all tables to enforce strict security boundaries.
-- Note: Supabase bypasses RLS for service_role automatically.
-- We do NOT add public permissions on biometric tables.
ALTER TABLE public.departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance_corrections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.face_descriptors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.office_geofence ENABLE ROW LEVEL SECURITY;

-- RLS Policies

-- 1. Departments Policies
CREATE POLICY "Allow select for authenticated and anon" ON public.departments FOR SELECT USING (true);
CREATE POLICY "Allow admin write" ON public.departments FOR ALL TO authenticated USING ((auth.jwt() -> 'user_metadata' ->> 'role') = 'admin') WITH CHECK ((auth.jwt() -> 'user_metadata' ->> 'role') = 'admin');

-- 2. Employees Policies
CREATE POLICY "Allow select for own profile or admin" ON public.employees FOR SELECT TO authenticated USING (email = auth.jwt() ->> 'email' OR (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin');
CREATE POLICY "Allow admin write" ON public.employees FOR ALL TO authenticated USING ((auth.jwt() -> 'user_metadata' ->> 'role') = 'admin') WITH CHECK ((auth.jwt() -> 'user_metadata' ->> 'role') = 'admin');

-- 3. Attendance Policies
CREATE POLICY "Allow select for own attendance or admin" ON public.attendance FOR SELECT TO authenticated USING (employee_id = (SELECT id FROM public.employees WHERE email = auth.jwt() ->> 'email') OR (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin');
-- Write is service_role only (no INSERT/UPDATE/DELETE policies for public or authenticated).

-- 4. Attendance Corrections Policies
CREATE POLICY "Allow select for admin only" ON public.attendance_corrections FOR SELECT TO authenticated USING ((auth.jwt() -> 'user_metadata' ->> 'role') = 'admin');
-- Write is service_role only (no INSERT/UPDATE/DELETE policies for public or authenticated).

-- 5. Face Descriptors Policies
-- Service role only. No policies defined, so all access from anon/authenticated is blocked.

-- 6. Devices Policies
CREATE POLICY "Allow select/write for admin only" ON public.devices FOR ALL TO authenticated USING ((auth.jwt() -> 'user_metadata' ->> 'role') = 'admin') WITH CHECK ((auth.jwt() -> 'user_metadata' ->> 'role') = 'admin');

-- 7. Audit Logs Policies
CREATE POLICY "Allow select for admin only" ON public.audit_logs FOR SELECT TO authenticated USING ((auth.jwt() -> 'user_metadata' ->> 'role') = 'admin');
-- Write is service_role only (no INSERT/UPDATE/DELETE policies for public or authenticated).

-- 8. Logs Policies
CREATE POLICY "Allow select for admin only" ON public.logs FOR SELECT TO authenticated USING ((auth.jwt() -> 'user_metadata' ->> 'role') = 'admin');
-- Write is service_role only (no INSERT/UPDATE/DELETE policies for public or authenticated).

-- 9. Locations Policies
CREATE POLICY "Allow select for everyone" ON public.locations FOR SELECT USING (true);
CREATE POLICY "Allow admin write" ON public.locations FOR ALL TO authenticated USING ((auth.jwt() -> 'user_metadata' ->> 'role') = 'admin') WITH CHECK ((auth.jwt() -> 'user_metadata' ->> 'role') = 'admin');

-- 10. Settings Policies
CREATE POLICY "Allow select for everyone" ON public.settings FOR SELECT USING (true);
CREATE POLICY "Allow admin write" ON public.settings FOR ALL TO authenticated USING ((auth.jwt() -> 'user_metadata' ->> 'role') = 'admin') WITH CHECK ((auth.jwt() -> 'user_metadata' ->> 'role') = 'admin');

-- 11. Office Geofence Policies
CREATE POLICY "Allow select for everyone" ON public.office_geofence FOR SELECT USING (true);
CREATE POLICY "Allow admin write" ON public.office_geofence FOR ALL TO authenticated USING ((auth.jwt() -> 'user_metadata' ->> 'role') = 'admin') WITH CHECK ((auth.jwt() -> 'user_metadata' ->> 'role') = 'admin');

-- 12. Challenge Nonces Infrastructure Table (Service Role Only)
CREATE TABLE IF NOT EXISTS public.challenge_nonces (
  session_id VARCHAR(100) PRIMARY KEY,
  challenge_type VARCHAR(50) NOT NULL,
  created_at BIGINT NOT NULL
);
ALTER TABLE public.challenge_nonces ENABLE ROW LEVEL SECURITY;

-- 13. Rate Limit Hits Infrastructure Table (Service Role Only)
CREATE TABLE IF NOT EXISTS public.rate_limit_hits (
  key VARCHAR(255) PRIMARY KEY,
  hits INT NOT NULL,
  reset_at BIGINT NOT NULL
);
ALTER TABLE public.rate_limit_hits ENABLE ROW LEVEL SECURITY;
